### ISSUE TITLE
Create tables for census data

### ISSUE THREAD

**Issue by dmcglone** [azavea/transit-center-viz#15]
Tract-level census variables
Rows: each tract
ID Columns: tract unique ID, msa name, MSA unique ID, geom, state (?)
Value Columns: [change in each census variable 2006-2015]
Geom: Polygon (census tracts)

**Comment by eneedham** [comment]
Pulled data for the following tables from American Fact Finder for the years 2010-2015 ACS:

DP02
DP03
DP04
DP05

Series of R script combine these datasets, select and rename variables, bind them together, calculate change, and join them to census tracts.
