### ISSUE TITLE
Download National Transit Data

### ISSUE THREAD

**Issue by dmcglone** [azavea/transit-center-viz#3]
Unlinked passenger trips, by agency
- [x] Average speed - revenue service miles / revenue service hours
- [x] Median or Average Fare - total fare revenue/unlinked passenger trips
- [x] Farebox Recovery Ratio
- [x] Revenue service hours - sum total hours vehicles spend on the road
- [x] Budget data - total operating expenses

**Comment by simonkassel** [comment]
farebox recovery ratio is computed by dividing the system's total fare revenue by its total operating expenses
