### ISSUE TITLE
deploy app on transitcenter repo

### ISSUE THREAD

**Issue by eneedham** [azavea/transit-center-viz#36]

**Comment by hectcastro** [comment]
Do we have a sense for what day this'll fall on, and what the process might look like? For example, would we transfer things to their GitHub and then get on a call to work out the details? Do that via email? Trying to make sure there is a block of time available for this in either situation for a given day.

**Comment by eneedham** [comment]
Our deadline for delivery is November 10th. I'm open to suggestions for the process. The client seems pretty tech savvy so it might be possible to try with an instructional email and have a call scheduled in case we need it.

**Comment by hectcastro** [comment]
Sounds good (especially if they're savvy). Going to link to a few references here that I plan to include in the email later:

- https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/#transferring-to-another-organization
- https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages

If you have contact with them now, it might be beneficial to start asking questions about the transfer:

- Are we transferring to another GitHub user account or an organization? Do they still have to create it?
- Are they going to be OK with something like https://whatever.github.io/transit-center-viz/, or will they want to make a custom domain work (`transit-center-viz.org`)?
- Will they be providing feedback on the deliverable before the transfer, or after? If after, we may need to coordinate access to be able to make changes.

**Comment by eneedham** [comment]
- they created a repo and shared credentials. He is fine with us just logging in and setting it up.
- they are okay with that. The repo name should be `ridership`.
- providing feedback tomorrow but he also wants to check in Monday in case they've identified any bugs. In which case we would need a way to address them. Since we have the credentials, maybe this won't be an issue.

**Comment by hectcastro** [comment]
Summary of the steps I took to complete this:

- Created a `ridership` repository in their GitHub account
- Used `rsync` to copy over the state of `master` in this repository, minus things we want to keep out (`data_analysis`, `.git`, `node_modules`, etc.)
- Created a GitHub personal access token with their account to support pushing to `gh-pages` from CI
- Connected the repository to the free CI service, Travis CI
- Configured the personal access token with Travis CI, kicked off a build of `master`

Relevant URLs:

- https://github.com/transitcenter/ridership
- https://transitcenter.github.io/ridership/
