### ISSUE TITLE
Legends for map layers

### ISSUE THREAD

**Issue by eneedham** [azavea/transit-center-viz#53]
-Only one layer will ever be on the map at once
-Some layers are choropleth
-Some layers are graduated symbols, would need color ramp in legend as well as circle size if possible

**Comment by dmcglone** [comment]
Classes and color scheme assignments for each layer located in these two files:

F:\Azavea_CartographicServices\TransitCenter_RidershipVisualization\data\cartography\ntd_cartocss.css

F:\Azavea_CartographicServices\TransitCenter_RidershipVisualization\data\cartography\census_cartocss.css

Also attached
[cartocss.zip](https://github.com/azavea/transit-center-viz/files/1455615/cartocss.zip)
