### ISSUE TITLE
Populate charts modal

### ISSUE THREAD

**Issue by eneedham** [azavea/transit-center-viz#55]
Looks like there is a second modal that appears when you click on the charts, I think this is supposed to have the chart in it but larger. Currently it is empty. 

This is not something that the client knows about so it is not crucial at this point.

**Comment by CloudNiner** [comment]
I would strongly suggest that we remove whatever was intended for that modal. _Maybe_ we could leave it in if it just showed some copy but we should add a button or something that triggers it. The current trigger (the whole card) messes with chart interactivity.

**Comment by eneedham** [comment]
I am fine with removing the whole modal. It was an optional idea we had awhile back and its not something that the client is expecting. Is that something you can do or should I ask someone else?

**Comment by CloudNiner** [comment]
Already removed in #47
