### ISSUE TITLE
Not all MSA's zoom to tract level on selection

### ISSUE THREAD

**Issue by mmcfarland** [azavea/transit-center-viz#82]
Some areas zoom to an area that is still at the national level instead of the MSA/tract level.  Might be a fitBounds thing.

Example MSA: Denver, LasVegas

Select either in the dropdown or click the popup link and tracts are not visible yet.

**Comment by CloudNiner** [comment]
Almost certainly a fitBounds issue where its possible that the zoom level for the bounds, depending on things like viewport size, isn't quite high enough to break the threshold. The change to only swapping the layers on dropdown or popup interaction should address this.

**Comment by mmcfarland** [comment]
> The change to only swapping the layers on dropdown or popup interaction should address this.

Is this under way under a separate effort?  If so, I'll ignore.

**Comment by CloudNiner** [comment]
This is underway, working on it now.
